### ISSUE TITLE
Bug: Registration always returns empty form on Submit

### ISSUE THREAD

**Issue by baer** [stormpath/stormpath-express#87] opened 2015-09-04 08:00 UTC
The Empty handler always gets called on submit of a Registration form
https://github.com/stormpath/stormpath-express/blob/master/lib/register.js#L160-L164

```js
  app.use(stormpath.init(app, {
    website: true,
    client: {
      apiKey: {
        id: config.stormpath.id,
        secret: config.stormpath.secret
      }
    },
    application: {
      href: config.stormpath.url
    },
    web: {
      register: {
        fieldOrder: [ "givenName", "surname", "email", "password", "passwordConfirm" ]
      }
    }
  }));
```
stompath-express#2.0.1
node 0.12.7

**Comment by mcmo** [comment] 2015-09-04 21:15
Same here.  Registration form gets re-rendered on submit, whether the password is valid or not.  No error messages.  User account not created.
```javascript
stormpath.init(app, {
  client: {
    apiKey: {
      id: config.id,
      secret: config.secret
    }
  },
  application: {
    href: config.href
  },
  web: {
    register: {
      enabled: true,
      uri: '/register',
      fieldOrder: [ "email", "password", "passwordConfirm" ]
    }
  }
});
```
stompath-express 2.0.1
node 0.12.7

**Comment by ppitonak** [comment] 2015-09-07 10:37
the same problem with stormpath-express 2.0.2

**Comment by rdegges** [comment] 2015-09-16 18:40
Working on this now. Will get this fixed today.

**Comment by rdegges** [comment] 2015-09-16 18:54
Writing tests for this now -- our old tests clearly weren't catching this for some reason. Once I get all the testing reproducing things, I'll work on a fix. Will update status here as I make progress.

**Comment by baer** [comment] 2015-09-16 21:24
> Once I get all the testing reproducing things, I'll work on a fix.

Cleary you're doing it right!

**Comment by rdegges** [comment] 2015-09-16 22:36
So, still writing tests (had some calls in between), but am improving test coverage to 100% as I'm going through this. Going to make sure there are 0% bugs in this registration stuff.

**Comment by rdegges** [comment] 2015-09-17 00:25
Ok, been writing a LOT of tests. Found some issues with this, and some other odd edge cases as well. Will take a bit longer than I initially thought to fix everything. Will keep updating this as progress is made. I'll likely have to wrap this up tomorrow.

**Comment by baer** [comment] 2015-09-17 04:55
👏🍻 thanks for all of your hard work!

**Comment by bassie1995** [comment] 2015-09-22 11:50
Has there been any progress on this?

**Comment by rdegges** [comment] 2015-09-22 20:23
This is almost done -- been taking a while due to other work constraints. Should ship this very soon =)

**Comment by rdegges** [comment] 2015-09-23 01:06
Just merged this in. Will cut a release first thing in the morning once I have a chance to update docs / etc.

**Closed** 2015-09-23 01:06 UTC

**Comment by baer** [comment] 2015-09-23 01:36
:confetti_ball: That's a HUGE PR. Nice work.

**Comment by rdegges** [comment] 2015-09-23 05:06
Thanks, hah. Took a lot of hacking, but it is muchhh better now. And VERY well tested.

**Comment by rdegges** [comment] 2015-09-24 18:06
This has been released!
