### ISSUE TITLE
extreme slowness when adding expand....

### ISSUE THREAD

**Issue by braindevils** [stormpath/stormpath-express#52] opened 2015-02-12 08:58 UTC
When enabling expandGroups or expandProviderData etc, the response times (caching in memcached enabled!) go from a few millisecs to over 1 second. Seems that info is not being cached? Also, when using the middleware (app.use), but not using a loginRequired on that route, is still really slow.

**Comment by rdegges** [comment] 2015-02-12 16:50
Are you using the latest release? We had some issues with this several releases ago.

The way it works is as follows:

- On each request, we'll fetch (in parallel) whatever expanded resources you have specified (groups, customdata, etc.).
- The first time it happens, this means 1 API call for each resource.
- The second time it happens, it means 1 API call from the *cache* for each resource.

When I'm testing this locally, it gives me very fast response times using the default in-memory cache.

You may also want to verify your cacheTTL settings and whatnot -- those affect how long these caches last.

**Comment by romant** [comment] 2015-02-13 01:38
Hi @rdegges - this did come back. I took out the grouping and put it into the customData instead, and manage manually, as the latency was too great here in Australia. So I'll mirror @braindevils's latency point on the group expansion.

**Comment by rdegges** [comment] 2015-02-13 01:43
Hey @romant, thanks for the info! I'll have to do some further debugging on this with my partner in crime, @robertjd early next week and get back to ya'll!

**Comment by romant** [comment] 2015-02-20 04:06
@rdegges any update? Eagerly awaiting :)

**Comment by rdegges** [comment] 2015-02-20 17:35
Hey @romant, sorry for the delay! I've been working with @robertjd on this, but we need some more debugging to get to the root cause. We've have some time blocked off Monday to work on this, so hopefully I can give you an answer then =)

**Comment by romant** [comment] 2015-03-11 00:27
Hi @rdegges is there anything you can share on this?

Thank you.

**Comment by rdegges** [comment] 2015-03-11 00:28
Hey @romant, sorry not yet! Robert and I didn't get a chance to pair on this yet. We ended up having some illness / travel between the two of us, so we're hoping to get to this sometime this week.

Sorry for the slow turnaround time, been kinda crazy over here.

**Comment by romant** [comment] 2015-04-06 03:47
Hi @rdegges. I haven't used the feature since its inception due to this bug. Am certain there are others affected.

Any eta on this one? Or if fixed already - please update.

Many thanks!

**Comment by rdegges** [comment] 2015-04-07 00:53
Hey @all,

This is sitll being worked on in the underlying Node.js SDK. It's apparently quite a bit trickier to solve than originally thought, which is why this issue has been stagnant.

We're making progress on the issue and will try to get it fixed soon. Sorry for the delay everyone!

In the meantime, we've pushed out quite a few performance updates to the core stormpath API, so if you want to implement expansions now, you're more than welcome to -- the slowdown should be minimal.

**Comment by romant** [comment] 2015-05-29 03:06
One marginal workaround for this would be to offer local (not just US) instances of Stormpath. @rdegges any thoughts / view on when this will be possible?

Thanks.

**Comment by omgitstom** [comment] 2015-09-28 18:55
This is a node issue.  It is logged here: https://github.com/stormpath/stormpath-sdk-node/issues/209

When it is fixed in node, this issue should be resolved.

**Closed by omgitstom** 2015-09-28 18:55 UTC
Labels: bug
